### ISSUE TITLE
Listen to database changes

### ISSUE THREAD

**Issue by yrezgui** [louischatriot/nedb#175]
Hi guys,
is there a method to track the database changes like this : http://pouchdb.com/api.html#changes

It's useful for synchronizing and many other cases.

Thanks.

**Comment by gunn** [comment]
+1 - especially important for running in the browser.

**Comment by jure** [comment]
You could manually couple your database operations with custom events, e.g.:

```
db.insert([{ a: 5 }, { b: 42 }], function (err, newDocs) {
  eventEmitter.emit('insert', newDocs);
});
```

**Comment by JamesMGreene** [comment]
:+1:

**Comment by JamesMGreene** [comment]
@louischatriot: Would you be open to this idea in general?  If so, is there a particular API you would have in mind?  If so, please let me know what you'd prefer and I'll consider coding up a PR.

Offhand, here is my idea for such an API, loosely based on [Meteor's `Mongo.Cursor#observe` callbacks](http://docs.meteor.com/#/full/observe)... because I really hate the PouchDB API for it.  :smile:

```js
var Datastore = require('nedb');
var db = {
  users: new Datastore('path/to/users.db')
};

db.users.on('added', function(newDocument) {  /* ... */  });

db.users.on('changed', function(newDocument, oldDocument) {  /* ... */  });

db.users.on('removed', function(oldDocument) {  /* ... */  });
```


While we're on the subject, did you have any particular qualms with PR #246?  It appears the author (@misha) had a very similar idea to my own &mdash; though they also had what I would consider to be an extremely unnecessary `changes` method &mdash; but ended up self-closing it after 1 week because they said they wouldn't be able to make further updates if you desired any.

**Comment by JamesMGreene** [comment]
See also PR #156.

**Comment by JamesMGreene** [comment]
Since this issue is still open, I'll add my comments here.

FWIW, here's a Gist of a derivative class I use ("EventedDatastore.js") in order to add eventing: https://gist.github.com/JamesMGreene/0e0b2506c7bd2a2557f7

I've recently updated that Gist accordingly since the `Datastore` class in `nedb@^1.7.0` now inherits from the `EventEmitter` class.

**Comment by louischatriot** [comment]
Yep this idea was developed in 2 other issues I think. So my point of view here is that I do like events and the pubsub pattern, and I understand why some people would want that. That said I do not think this should be part of nedb, which is why I have decided against implementing it. The main reason is that the usecase for events are very application-specific, so any implementation will be necessarily a pain to use in most usecases. This is best kept at application level.

I'll close the issue.
