### ISSUE TITLE
Support for distinct operator

### ISSUE THREAD

**Issue by elynnaie** [louischatriot/nedb#185]
NeDB seems to be messing support for a "distinct" operator. Is this something that can be considered, and/or is there a known workaround?

**Comment by KeitIG** [comment]
@louischatriot Would you accept PR for distinct operator support ?

**Comment by JpEncausse** [comment]
Hi,
About this issue how do you get all the distinc set of values of a given field ?

- I need to suggest categories (aka tags) of an article.
- I have many fields with a defined set of values I was thinking or retrievling them like that

Otherwise if I have to maintain my own index it will be complicated.
Can I get all the keys of an index on a given field ?

Thanks
