### ISSUE TITLE
README misleading when comparing to SQLite

### ISSUE THREAD

**Issue by nakedible** [louischatriot/nedb#265]
The README says: 
> You can think of it as a SQLite for Node.js projects, which can be used with a simple require statement.

One of the major features of SQLite is that it is safe for multiple process use, even though it does not support concurrent modifications (there's locking for multiple concurrent transactions). The other major feature is that it is crash safe in the way that when a commit returns, the data is guaranteed to be synced to disk.

I think NeDB requires a big warning that data is not guaranteed to be persisted after callback returns, and that NeDB has no support for concurrent access from separate processes.

Great project, nevertheless!

**Comment by louischatriot** [comment]
NeDB doesn't support concurrent connections out of the box indeed, but it is crash safe (at least designed to be, still investigating the recent bug report). The readme intro is quite old though you're right, now nedb is well known enough not to need to be compared with another product.

**Comment by nakedible** [comment]
It is (or seems to be) crash safe in the manner that there should be no corruption in the case of crashes - but it is not crash safe in the manner that there would be a "commit" operation that would guarantee the changes have been persisted. Atleast I did not spot any `fsync` calls in the persistence module.

This means it cannot be used in any situation where you need to store something persistently before trying an action - such as storing a request id before sending a request to be able to query status or cancel it later.

**Comment by louischatriot** [comment]
There is no need to call fsync in the persistence layer as appendFile will guarantee data is persisted to disk before executing the callback.

**Comment by prust** [comment]
@louischatriot: Thanks for open-sourcing your work on nedb!

> appendFile will guarantee data is persisted to disk before executing the callback

I'm not so sure. My understanding ([in line with this SO answer](http://stackoverflow.com/a/17049877/194758)) is that node only implements thin async wrappers around file system calls and does not provide atomicity/durability guarantees because they're just calling [write(2)](http://man7.org/linux/man-pages/man2/write.2.html):

> A successful return from write() does not make any guarantee that
       data has been committed to disk.  In fact, on some buggy
       implementations, it does not even guarantee that space has
       successfully been reserved for the data.  The only way to be sure is
       to call fsync(2) after you are done writing all your data.

IOW, node will call the callback once the data is written to the OS's buffer cache, not when it is actually physically written. 

Scanning the node & libuv source code seems to confirm that it's just a thin async wrapper around write(2) & doesn't call fsync() under the hood (appendFile() calls [writeFile()](https://github.com/joyent/node/blob/master/lib/fs.js#L1135) with the "a" flag, writeFile() [calls fs.write()](https://github.com/joyent/node/blob/master/lib/fs.js#L1049) repeatedly until the data is written and fs.write() calls [writeBuffer()](https://github.com/joyent/node/blob/master/lib/fs.js#L591) or [writeString()](https://github.com/joyent/node/blob/master/lib/fs.js#L608) on node's native fs binding, which [call uv_fs_write()](https://github.com/joyent/node/blob/master/src/node_file.cc#L904) and [make the system call write(2)](https://github.com/joyent/node/blob/master/src/node_file.cc#L845) respectively. The [implementation of uv_fs_write()](https://github.com/libuv/libuv/blob/v1.x/src/unix/fs.c#L1148) is hard to for me follow, but it doesn't look like it calls fsync() -- it looks like fsync() is only called when the user calls fs.fsync() or fs.fsyncSync() directly).

That said, because of the performance hit, I'm not sure you would want to call fs.fsync() or fs.fsyncSync() implicitly, it might be the kind of thing the user should call or configure explicitly if they need a guarantee of durability.

**Comment by louischatriot** [comment]
@prust thanks for the details!

After diving into the issue I agree that this was actually an issue. As of v1.4.1, NeDB will always force OS to physically write data to disk whenever a compaction or database load happens, so that you can never lose the whole database in case of a machine crash. It doesn't flush on every append for performance reasons, but potential data loss in that case is very limited, a few docs at most. That's what major databases do.

Readme: https://github.com/louischatriot/nedb#persistence

Note that `fsync` doesn't work on Windows. Not sure whether that's an issue with my machine or you simply can't `fsync` on Windows. I raised the question with the Node team but any help appreciated!

**Comment by nakedible-p** [comment]
All major databases sync after each transaction - which, with autocommit, is after each document. This is the part in SQLite explaining this: https://www.sqlite.org/pragma.html#pragma_synchronous . A similar option is in MySQL: http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit . Same for PostgreSQL: http://www.postgresql.org/docs/9.1/static/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT . Here it is for CouchDB: http://docs.couchdb.org/en/1.6.1/config/couchdb.html#couchdb/delayed_commits .

Choosing not to sync after each write is fine as long as it is mentioned - the readme bit is good, except for the part that says it works similarily to major databases (it also has a typo "phyiscal").

However, the compaction implementation currently is dangerously wrong. It is renaming `tempFilename` to `filename` before calling fsync which means that a crash there gives a very real chance that `filename` exists and is empty while `oldFilename` still contains the full database data. This can be fixed by moving the `flushToStorage` call to happen before the rename. Secondly, the first `flushToStorage` is useless as it will only ensure the data inside the file is synced, which is already handled by the normal crash recovery - it does not enforce that the rename has happened. Thirdly, nothing ensures the directory entry is flushed, meaning that a correct response from the filesystem (in a crash) could be that the new file does not appear in the directory, but the old file is unlinked (though note that most filesystems do not behave this way). You need to fsync the directory before calling `ensureFileDoesNotExist` on `oldFilename` at the very least. If you wanted the rename from `filename` to `oldFilename` be synchronized to disk (and the unlinks before it) as per the comment, then you should replace the first `flushToStorage` call with something that calls fsync on the directory.

Note that I have not fully audited the implementation against corruption in a crash, these were just the first things to come to mind when looking at the implementation. Ensuring data integrity has to be either taken very seriously, because it is very hard to get right, or no integrity claims should be made.

**Comment by louischatriot** [comment]
The code you see on the master branch is still not live, as it was indeed not crash-proof. I unpublished v1.4.1 while I'm working on the final version. The readme will be accurate once this version is pushed.

It's taking a long time since I'm not a filesystem expert so I'm having a friend review this part of the code. I may be interested in having some more pair of eyes look at this part of the code before republishing v1.4.1, as you say this is both crucial and very hard to get right.

**Comment by nakedible-p** [comment]
Okay, that sounds great! I can take a peek later on to see if I can spot anything amiss.

**Comment by louischatriot** [comment]
I finished rewriting the crash safe write function, mimicing how Redis AOF basically works (see http://oldblog.antirez.com/post/redis-persistence-demystified.html).

See https://github.com/louischatriot/nedb/blob/master/lib/storage.js

Basically what it does is:
1) fsync directory so that datafile is sure to be linked to from the directory
2) fsync datafile if it exists. At this point we are guaranteed that datafile is up to date, and a crash during steps 1 or 2 will not corrupt the datafile
3) Write data to a temp datafile, then fsync it
4) Rename temp datafile to datafile and fsync directory

And upon reload, always use the contents of the datafile except in the (pathological) case where datafile doesn't exist but temp datafile does, which cannot be done by nedb (the user needs to do it manually, at which point we can assume he's trying to crash nedb on purpose !).

Now if there is a crash during steps 1 or 2, the datafile is no more corrupt than before, no data that was already persisted to disk is lost. Of course everything that was in the kernel buffer cache is lost but on pretty much all OSes that's at most 30s of data.

If there is a crash during step 3 or 4, the temp datafile may be corrupt and incomplete. In that case we use the datafile, we have lost the same data we lost in step 2

After step 4 the new data is persisted fully to disk. The rename being atomic we are guaranteed at this stage that the temp datafile doesn't exist anymore. The fsync on the directory is necessary though, or a crash right after step 4 could lose the same data as above.

I'm interested in any comments you guys might have on this, more eyes are always better :)

**Comment by nakedible-p** [comment]
The algorithm looks to be correct, but I'm not sure if you've defined what is the consistency guarantee.

An obvious one is that compaction should never cause any rollback - meaning that any data that has already reached stable storage is not erased by compaction.

That requires *only* doing fsync on the temp datafile contents before rename (step 3). Everything else is superfluous.

Another one might be that compaction means also that all data is flushed to disk, meaning that a compaction is also a commit.

If that is wished then fsync on the directory after rename is also needed (step 4).

Steps 1 and 2 are just commits on data before compaction, which do not really serve a purpose - except if we believe that compaction is a long running operation and we wish to ensure that the latest "diff" before compaction is persisted to disk (a fast operation) as we might crash during the long compaction.

Also, the `flushToStorage` operation seems a bit weird. It doesn't close the file if fsync errors and lines 59 and 60 are probably to be removed?

**Comment by louischatriot** [comment]
There is no real consistency in the RDBMS sense as NeDB doesn't implement transactions, foreign keys, constraints and so on ... Integrity is guaranteed by the append-only, one-line-per-operation format of the datafile. Any corrupt line is discarded, which can be the case if there is a power loss during an append, but that can only affect the end of the file so that's the same as losing latest data.

Also there cannot indeed be any rollback, since the datafile is replaced only after a successful write.

Durability is not enforced on every write, only during compaction since a power loss at that moment can result in 100% data loss. For all appends to the datafile durability is the responsibility of the OS, which usually syncs to the disk every 30 seconds so you cannot lose more than 30 seconds of data. That's what most databases do (they do provide an option to force sync on every wrtie though, nedb doesn't).

fsync on steps 1 and 2 are actually useful only when the database is first created. As you say once it is created they are not needed. Still unsure as to keep them.

Good catch on flushToStorage, line 57 should be removed and file closed if fsync fails anyway.

Thanks for your help !

PS : this code doesn't work on Windows, as it seems that Windows's counterpart to fsync, `FlushFileBuffers` cannot be called on directories. That's not a show stopper but do you whether that's correct ? Here is the article I got this info from : http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/

**Comment by louischatriot** [comment]
I just pushed the new `flushToStorage`, if you want to look at it. Still investigating the Windows fsync but I'll probably simply not fsync directories on Windows, as stated above there is no risk of 100% dataloss except the very first time the database is created. I

**Comment by louischatriot** [comment]
I just published v1.5.0, which includes this guarantee on durability.
