### ISSUE TITLE
Persist InMemoryOnly datastore

### ISSUE THREAD

**Issue by chaicko** [louischatriot/nedb#285]
Hi, is there a way to persist (save to disk) a Datastore instance once it has been loaded with the option `inMemoryOnly` set to `true`?

Specifically, the use case is the following:

```javascript
// Memory only datastore with manual loading
var Datastore = require('nedb')
  , db = new Datastore({ filename: 'path/to/datafile', inMemoryOnly: true });
db.loadDatabase();

// Do some work with the Datastore, i.e., insert several docs

// Persist database in memory to 'path/to/datafile'????
```

thanks for your great tool!

**Comment by louischatriot** [comment]
That's not possible, and not trivially done either considering all os fail-safe mechanisms in place in the persistence module. I also don't really understand why you would want this instead of letting NeDB always persist data on disk. Disk space is cheap and if you're looking for performance and scaling you will be better off not using nedb but mongodb instead.

**Comment by szwacz** [comment]
If you really need to you can create second instance of NEDB (this time with persistence) and copy all data from one DB to another.

**Comment by chaicko** [comment]
Actually I was looking for a possible use case using NeDB directly. Is only for a demo and certainly are workarounds to having this. Anyway, thanks for the replies!
