### ISSUE TITLE
Browser version: loading database causes quota exceeded error due to rename

### ISSUE THREAD

**Issue by jthrilly** [louischatriot/nedb#302]
Hi

I'm using nedb with wonderful results in a mixed nwjs/browser setting.

Lately I have come across a problem whereby loading a database that is more than half the localStorage quota will cause a QuotaExceededException, at least in Chrome 44. 

The stacktrace shows the failure is happening because nedb is renaming from myDatabase~ to myDatabase during the loadDatabase call, though I can't tell why it should be doing that.

It seems counter-intuitive that a read operation should cause a quota exception – afterall the data has already been stored!

Any thoughts?

**Comment by louischatriot** [comment]
Hello Josh,

This mechanism is indeed strange at first sight but is used by the server version of nedb. The goal is to use temporary files when the cached database is persisted (which happens at startup in loadDatabase and depending on configuration can happen when the user requests it or at regular intervals) to avoid data loss issues if the machine crashes. Without this system if the machine crashes when nedb is rewriting the data file, the data file becomes empty and all data is lost.

It doesn't seem to be useful in a browser setting I agree, but the way the code is factorized makes it use this system. There are ways to fix it but since I'm quite short on time I'd first like to understand the use for your app, if you are already reasching 1/2 of the limit isn't there a good chance you reach the limit too ?

**Comment by jthrilly** [comment]
Thanks for the reply.

My app is for social research and stores a network-like data structure. The majority of the volume of the data results from every interaction with the app (touch or mouse click) being logged, which allows the network to be reconstructed and the interactions analysed. You're right that there's a good chance I could use the limit, but I would like to be able to use as much data as possible, and then catch the quota exception myself in order to manage it within my application logic.

There are a few options: 
- Could there be an optional parameter for loadDatabase which either loads the data with the risk of data loss during a crash? It could even be a different method which is browser specific.
- Could there be a read-only loadDatabase that would at least allow the app to load?
- Could you handle the quota exception within nedb, and use one of the above options within the catch statement?

I can look into implementing this, if needs be.

**Comment by jthrilly** [comment]
Any thoughts?

**Comment by louischatriot** [comment]
As of v1.4, NeDB automatically selects the best method to persist data on the browser (IndexDB then WebSQL then localStorage), so the limit is removed. WARNING: it's not back compatible with v1.3, but that should not be a major issue as user apps can resync entirely.

Also in the browser the crash safe mechanism is not used anymore, so you get the full available disk space, way more than 5MB (typically in 100s of MB)
