### ISSUE TITLE
Open a db two times simultaneously

### ISSUE THREAD

**Issue by zevero** [louischatriot/nedb#314]
I have a suspicion, that opening a nedb file two times simultaneously results in data loss... Even if the second one is only opening it for a short time and only reading ...
May this be related to data compaction?
Is there a way to open a file a second time with data compaction disabled?

**Comment by louischatriot** [comment]
Indeed, working on the same datafile with two different datastores will produce weird results. That's not due to compaction but synchronization with the cache. There was a project to create a HTTP server to be called with nedb commands but I will not have the time to complete it.

Feel free to continue it or implement a locking system, I can review PRs.
