### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by waldemarnt** [louischatriot/nedb#320]
Hello guys.
I'm using nedb and I'm getting this error.
Someone else knows what happened?
(is a nw app)
![screenshot-developer tools - file ---home-waldemarnt-node_projects-value-selling-src-index html](https://cloud.githubusercontent.com/assets/5835706/10352519/f59a7f94-6d25-11e5-80a7-61fc8a94c570.png)

Thanks for your attention guys

**Comment by bdfoster** [comment]
Can't call NeDB more than once for the same filename.

**Comment by waldemarnt** [comment]
Thanks for the reply bdfoster, are you right, i tried to open more than one.

**Comment by martinsookael** [comment]
In this case, is usage like this acceptable (or would it create performanceissues / problems with updated data not being available)?
```
var Datastore = require('nedb')
  , db = {};

function getDB(table) {
  if(db[table]) {
    return db[table];
  } else {
    var tableFile = table + '.json';
    var thisDb = new Datastore({ filename: tableFile });
    db[table] = thisDb;
    return thisDb;
  }
}

// usage
var thisDb = getDB(table);
thisDb.loadDatabase(function (err) {
  // perform something  
});
```

**Comment by bdfoster** [comment]
The code looks kind of messy from a maintainability point of view, it
peobabky will work fine, but here's what I would do.

Your DB array is fine, but if the collection handle doesn't exist, create
it with 'autoload' set to true. Then, have a 'getDatastore' function that
gives back the loaded database. No need for two steps here, just return the
loaded datastore. If you need to handle an error differently on each
datastore, then pass a callback to the function, otherwise use some default
function to handle it.

My two cents, but again, it looks OK from what you've provided here (as far
as performance issues/problems are concerned).

In this case, is usage like this acceptable (or would it create
performanceissues / problems with updated data not being available)?

var Datastore = require('nedb')
  , db = {};

function getDB(table) {
  if(db[table]) {
    return db[table];
  } else {
    var tableFile = table + '.json';
    var thisDb = new Datastore({ filename: tableFile });
    db[table] = thisDb;
    return thisDb;
  }
}

// usage
var thisDb = getDB(table);
thisDb.loadDatabase(function (err) {
  // perform something
});

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/louischatriot/nedb/issues/320#issuecomment-214819354>
