### ISSUE TITLE
Can't handle multiple $not word ?

### ISSUE THREAD

**Issue by Yimiprod** [louischatriot/nedb#323]
I'm trying to do a request like this one (nedb@1.2.1):
```
{"$not":{"_deleted":true,"structure.ref":"sli_V1K30RIV"}}
```
It return every items even thoses with `_deleted = true` and the one with `structure.ref = sli_V1K30RIV`.

If i do
```
{"$not":{"_deleted":true}}
```
It correctly return all items without `_deleted = true`
```
{"$not":{"structure.ref":"sli_V1K30RIV"}}
```
It correctly return all items without `structure.ref = sli_V1K30RIV`

**Comment by louischatriot** [comment]
Please submit following bug reporting guidelines. I'll reopen then.

**Comment by cgestes** [comment]
What's wrong with this bug report?

**Comment by Yimiprod** [comment]
@louischatriot https://gist.github.com/Yimiprod/4138cd9f42c9aaeb2c5f here's a use case

**Comment by louischatriot** [comment]
Thanks for this clean report. That's not a bug but a problem in your code. When you write `{ $not: { _deleted: true, ref: 4 } }` nedb will select all documents that do not match the query `{ _deleted: true, ref: 4 }`. This query tries to select all documents where `_deleted` is true AND `res` is 4, and there is no document that matches, which is why all docs match the `$not` query.

The inverse of both is `{ $not: { $or: [{ _deleted: true}, {ref: 4}] } }`. A bit convoluted I know but that's how Mongo rolls :)

@cgestes the readme explains.
