### ISSUE TITLE
Database will hang on update if callback is undefined

### ISSUE THREAD

**Issue by tlaanemaa** [louischatriot/nedb#352]
I'm not sure if I'm doing something wrong here but this seems like a bug to me.

Anyway, if you pass undefined as a callback function to update function then it seems to hang. 
I provided an example below, toggle between the update rows to see how the output differs

<pre>
var nedb = require('nedb');
var path = require('path');

var db = new nedb({filename: path.join(__dirname, './test.db'), autoload: true});
db.insert({item: 'foo', arr: ['a', 'b', 'c']});

db.update({item: 'foo'}, {$addToSet: {arr: 'h'}}, {}) // works
//db.update({item: 'foo'}, {$addToSet: {arr: 'h'}}, {}, undefined) //doesnt work

db.findOne({item: 'foo'}, function(err, data){
  console.log("err -> " + err)
  console.log(data)
})
</pre>

**Comment by bdfoster** [comment]
What version?

**Comment by louischatriot** [comment]
Thanks for submitting a bbug but please stick to the bug reporting guidelines as per the readme. You must have a, old version, this was fixed long ago.

**Comment by tlaanemaa** [comment]
Sorry for not using the correct bug reporting form.
The version I am using is 1.5.1 which seems like the latest version.

I will try to rewrite this in the correct bug reporting form

**Comment by louischatriot** [comment]
I understand where this comes from, and that's actually the expected behavior: if you supply `undefined` as callback, you are supplying a callback (`undefined`). As this callback is not a function unexpected behavior is bound to happen.

If you are curious the reason is in the executor, which treats undefined as "not a callback" but keeps it in the arguments array, causing to grow one element too big.

As actually supplying `undefined` as callback is not supported, this behavior will not be changed.

**Comment by tlaanemaa** [comment]
Ok, thanks.

I found this when I wrote a function that handled my database updates. This function has a callback parameter that was passed directly into the update function but when my function's callback was not provided, the variable became <code>undefined</code> so that was passed into the update function instead. I guess I'll add a bit to my function that checks if the callback is provided and then passes it on or not accordingly.

Thanks for your help!
