### ISSUE TITLE
Make it possible to use the browser version without requiring the compiled code

### ISSUE THREAD

**Issue by paglias** [louischatriot/nedb#359]
I'm using webpack and I'd like to require the browser version of nedb as a normal module, not the compiled version that has all the dependencies bundled and makes it impossible to optimize the required code.

So for example if I use `localForage` and `nedb` in my code I'll end up with 2 versions of `localForage`, the one I required and the one bundled inside nedb

**Comment by louischatriot** [comment]
That's not a planned feature since it doesn't cause any conflict. To be frank I don't find this less-than-optimality to be a real problem, but you could always use the source and build your own js including NeDB from sources using browserify. The build script is pretty clear so you can start from that and adapt to your custom code, even though again in my opinion you are going to spend a lot of time and energy on what I consider a secondary problem.

**Comment by paglias** [comment]
@louischatriot well the problem is not critical but still doesn't make sense having to load some modules twice in my opinion
