### ISSUE TITLE
Every update clones my doc.

### ISSUE THREAD

**Issue by roccomuso** [louischatriot/nedb#362]
I've tried a simple code:

    db.update({ _id: card_id }, { $set: { "device.is_on": is_on } }, {}, function (err, numReplaced) {
					  if (err) return reject(err);
					  resolve(numReplaced);
	});

And this is how my general doc looks like:

    { 
        _id: "......",
        type: 'xxx',
        device: {
                       is_on: true,
                       name: 'hello world'
                     }
    }

Every time I execute the code above, and i look into the DB file, I found a copy of the doc, with the same _id.
Is every update stored in the DB file? Is this a normal behaviour?

**Comment by roccomuso** [comment]
Maybe this is a normal behaviour: https://github.com/louischatriot/nedb/issues/197

So my question now would be: Should I compact my DB at regular intervals if my node app has frequent updates and can stay months without restarting?

**Comment by louischatriot** [comment]
This is the expected behavior indeed, as explained in the readme. DB compaction depends on how often you reload your app (compaction occurs whenever it's rreloaded) and how much HDD you have. Typically (10-20 GB HDD, not a lot of updates, application reloaded more than every month) it's not necessary.
