### ISSUE TITLE
how to handle if a db size larger then 256mb?

### ISSUE THREAD

**Issue by wlekin** [louischatriot/nedb#363]
i run a website with nedb and nodejs, everything work fine until it go down recently:
Error: toString failed
i find out if the db size larger then 256mb, v8 cannot read the string, what should i do!?

**Comment by louischatriot** [comment]
It seems to be either a limitation of Node/V8 that could be worked around by recompiling node with a larger kMaxLength constant, or more likely a RAM limitation on your machine. It might help to use the readline module instead of putting readFile result in memory, but I expect that the improvement will be no more than 2x.

**Comment by wlekin** [comment]
so I should not run a web page with nodejs? it cannot handle a large db at all?

**Comment by louischatriot** [comment]
Oh you mean you're using nedb browser ? In that case yes it cannot handle
large dbs, due to various limitations. Some could be lifted with a lot of
work, some can't. Server side the limit is around 1GB (remember, nedb is
NOT intended to be a full blown database such as MongoDB. If you expect
large datasets on the server, use Mongo).

**Comment by wlekin** [comment]
thanks... 
so I should switch to MongoDB? MongoDB dont have such a problem?
I really need some help cause this shutdown my company web page and my boss is fxxking with me right now... CRY

**Comment by lukasbestle** [comment]
MongoDB runs as a separate server process and can handle large databases. NeDB is made for simple applications.

**Comment by louischatriot** [comment]
Exactly. From what you say switch to MongoDB now. And don't forget to use the 64 bit version of MongoDB, the 32 bit version also comes with memory limitations.
