### ISSUE TITLE
support of {"$regex": "pattern"} as string

### ISSUE THREAD

**Issue by royaltm** [louischatriot/nedb#366]
mongo https://docs.mongodb.org/manual/reference/operator/query/regex/ supports this and using JSON serialized queries is a pain without regex patterns accepting value as strings.

If you try to do that, you get exception: "$regex operator called with non regular expression".

**Comment by louischatriot** [comment]
As explained in the readme, Mongo supporting a feature is not a reason for nedb to do so too. I don't think it is a pain to force yourself to use a regex, actually I think Mongo is wrong on that one.

**Comment by royaltm** [comment]
As explained in the issue the problem is that Regexp is not a std JSON datatype and serialisation is an issue. It's not that I don't want to user regexes, it's that there are circumstances when it's hard to use them. Why do you think Mongo is wrong on that one exactly?

**Comment by louischatriot** [comment]
Could you create a test case that shows how regexes impact serialization and what the effect is exactly? The bug reporting rules are here: https://github.com/louischatriot/nedb#bug-reporting-guidelines, I'll reopen the issue once you do.

I think that Mongo is wrong here because in my experience, being too lax on input is actually a good way to make your users confused. You end up with projects where different devs use different input methods to achieve the same result, impairing global readability and maintenability. But again if that causes an issue with serialization that's another matter.

**Comment by fridays** [comment]
Support for string regex would be great, it would then work well with this package for example: https://github.com/Turistforeningen/node-mongo-querystring
