### ISSUE TITLE
Persistend datastore gets emptied at application restart?

### ISSUE THREAD

**Issue by koasmsm** [louischatriot/nedb#441]
Hi, is this behaviour expected?

**Comment by louischatriot** [comment]
Hello no it's not and I would suspect an issue with your code as this has been reported by no one before (and hopefully so since a persistent db that does not persist would be quite useless!).

Could you file a bug report as per the bug reporting guidelines in the readme please? I'll then take a look at it - closing this in the meantime

**Comment by martinsookael** [comment]
Might be irrelevant (and also very little extra information is given) but when you are using containers like Heroku, Docker or Dokku these systems have an ephemerical file system, which means that the server gets restarted about once every 24 hours and all the files reset to the way they were in git. 

Since nedb database is also just a file, that means that also the database will be restarted with the rest of the server.
