### ISSUE TITLE
database file will clear after restart !

### ISSUE THREAD

**Issue by mahdisml** [louischatriot/nedb#502]
hi all , first of my code is : 

`
var Datastore = require('nedb'); 
var db = new Datastore({ filename: 'users.db', autoload: true });  
db.persistence.setAutocompactionInterval(0.1);

db.loadDatabase();

`
everything is ok with local host , and database will save every thick in my db file . (Database saved after server restarting)
but in heroku server , database is empty !!! 
i i think database saved in memory ! (not in my db file !!) Why ?!
i want keep my database in my db file in Heroku server !

**Comment by saswatds** [comment]
@mahdisml This is not a problem with nedb but with heroku. Heroku uses an Ephemeral filesystem due to which, on restart, your files (users.db) are cleared up and only the code persists. You could try some other means of storage like Amazon S3
[https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem](url)

**Comment by marcusjwhelan** [comment]
I would suggest not using a different database if you are able to work on a separate server. Unless you depend on being able to package your database with your application on deployment. Which would be the case for things like Electron apps.
