### ISSUE TITLE
typescript support so that we get type completion from objects returned in `find`

### ISSUE THREAD

**Issue by dheerajbhaskar** [louischatriot/nedb#508]
## Problem

1. I want to ensure type completion on objects returned in `find`
2. I want to make sure the correct type of doc is passed in an insert

## Context

I looked at the type definition file for nedb in DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nedb/index.d.ts)

I see passing of type `T` in a few places there. I was unsure where to pass types during instantiation because new object creation of nedb doesn't take in type information.

Please let me know if I can use types with nedb or pass in type information into nedb to get some type goodness.

If nedb doesn't support types, I'm sure I can just create a wrapper class for this, so no worries. Also, thanks for making such a neat library :)

**Comment by marcusjwhelan** [comment]
@dheerajbhaskar I used the nedb types in [nedb-shell](https://www.npmjs.com/package/nedb-shell), which is written in TypeScript, but it seems that the Types were written poorly and I have posted an issue for a fix. Also the creator seems to have left the project as is stating that it is a solid starting point and if you would like can expand on it on your own. Also nedb-shell does not support multiple instances, if you edit the db on one shell another shell will not recognize this edit. This is also true if you have an app running editing the db and you have a shell running, neither will see edits from one another since there is no file watchers. 

I would also take a look at some of the other issues. There is definite problems with memory usage when it comes to indexing large amounts of data. The entire document seems to be stored in memory when indexed.

**Comment by dheerajbhaskar** [comment]
@marcusjwhelan thanks for taking the time to write a reply. 

I shall take a look at nedb shell and see if I can contribute. I'll keep what you've said in mind. 

As regards to the high memory usage, there's a thing nedb-logger (https://github.com/louischatriot/nedb-logger)  mentioned on the Readme page. This is what the author has to say about it:

> If you mostly use NeDB for logging purposes and don't want the memory footprint of your application to grow too large, you can use NeDB Logger to insert documents in a NeDB-readable database

**Comment by dheerajbhaskar** [comment]
@marcusjwhelan I did take a look at nedb-shell. It might have been written in typescript but I don't think any type checking is done in docs before posting or after retrieving. There's no auto completion of doc properties either (there's of course auto completion of functions but that's not relevant here I think). 

Would you like to share a code snippet which does type checking before saving or after retrieving if there's such functionality? 

Thanks for taking the time

**Comment by marcusjwhelan** [comment]
@dheerajbhaskar I wonder if you can still utilize indices. About the auto completion of documents. The fact of the matter is that nedb would have to require a schema then, currently does not. TypeScript cannot guess the type inside the documents because it has nothing to reference. However if it were written to require a schema then the documents would have auto completion.

**Comment by dheerajbhaskar** [comment]
@marcusjwhelan if you don't mind, could you explain how indices would be helpful / relevant here? 

I kind of thought we'd run into the problem you mentioned. I've a possible solution described below. 

What I was thinking is having wrapper classes which proxy all of method calls to nedb and do type conversion (or type coercion?). I'm guessing since Javascript itself doesn't have any types, the entire wrapper class will be removed on compilation and you'll have zero performance impact but you'll still get type completion and checking in the editor  🙂

**Comment by marcusjwhelan** [comment]
@dheerajbhaskar indices cut down on search times. B-Trees hold the indices. Otherwise you will have a collection scan when searching for documents. The problem we were having is that I need to pull an entire collection down, wipe it, re-insert and ensure index on all elements on several collections.

As for the wrapper class. As far as I can tell I believe that would work. I wish Typescript would let you say hey this object that is of `any` it really is like this local `interface`. But TypeScript I don't believe will let you do that. I think it throws an error stating that type any is not of type "your interface".

**Comment by dheerajbhaskar** [comment]
That I understand about indices, but I'm unable to see how that's relevant from the types and autocomplete perspective. 

Typescript does allow that, it's called type assertion, see http://stackoverflow.com/a/35362350/1311745

I'll contribute back here or as another package if I end up implementing this. 

Thanks for taking the time all 🙂👍

**Comment by marcusjwhelan** [comment]
@dheerajbhaskar Myself and another developer are currently working on a TypeScript replacement. I just finished the AVL Btree for it last week. It is still in development. [teDB](https://github.com/tsturzl/teDB) the db, and  [binary-type-tree](https://github.com/marcusjwhelan/binary-type-tree) the btree
