### ISSUE TITLE
Is there a close method?

### ISSUE THREAD

**Issue by Roland1975** [louischatriot/nedb#81]
I'm using your great library and it seems there is no `close` method.

I'm developing an app using multiple databases (I mean multiple instances of `NEDB` object). Actually I'm wondering how you manage all the instances with no explicit call to `close`.

Thanks in advance

**Comment by RobertWHurst** [comment]
@herby Your setup and teardown functions are coupled to your tests. Otherwise there wouldn't be any point to them.

**Comment by herby** [comment]
Not coupled via shared db object instances, for God's sake. If I `setUp` a database content, it does not mean I pass the db instance to the tested code. Tested code loads database on its own (of course). And it means that I of course need close method to know `setUp` is finished and test can run (or, nedb should keep some internal cache and reuse the db when loaded again with the same file; but that us imo a level harder then being able to close).

Never mind, if you do not want to add close, don't, I use node-sqlite instead since it can close therefore it is nicely usable in tests.

Robert Hurst <notifications@github.com>napísal/a:

>@herbyYoursetupandteardownfunctionsarecoupledtoyourtests.Otherwisetherewouldn'tbeanypointtothem.ReplytothisemaildirectlyorviewitonGitHub.

**Comment by KardashDeveloper** [comment]
I faced similar issue, my tested function was updating database, than I wanted to check it in test, but there was still old information. When I opened db file in file system, it was updated, my function was working correctly, but tests weren't. Than I tried to do
db.loadDatabase();  
 before checking in tests, it worked.
