### ISSUE TITLE
How is writing and reading at the same time handled?

### ISSUE THREAD

**Issue by Removed-5an** [louischatriot/nedb#99]
What if I have two node scripts one writing to my db and another node script reading from the db. Do you have a concept of write-locks or how is this going to work?

**Comment by mawi12345** [comment]
It would be great if i could create a second instance of NeDB on the same database file in read only mode. I would allow scripts to open the db, query and exit.
I think the easiest way of implementing this is to load the the db in memory without compacting the file and then switch to in memory mode. This does of cause not enable synchronous writes, but i would like to run some simple scripts that only read data as cron jobs.

**Comment by louischatriot** [comment]
The desynchronization is quite a large issue for me in that scenario, since
it's sure to cause heavy headaches down the road. I assume from your
question that you are trying to access the same db from two distinct
processes. In that case the only clean way I see of doing so is to set up
an http server as a third process and query it from any number of processes
you want, read only or not. Pretty much what mongodb does. I had begun this
project but no time to finish it. Feel free to work on it as it can be
totally separate from nedb, and let me know if you finish it so that I can
link to it.
